"""modified tickets

Revision ID: 45ded1a0b5af
Revises: f98ff2f11052
Create Date: 2026-01-06 08:59:03.320871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ded1a0b5af'
down_revision: Union[str, Sequence[str], None] = 'f98ff2f11052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'is_deleted')
    # ### end Alembic commands ###
